---
- name: recreate install06.yml
  hosts: all
  
  vars:

    cpan_packages:
      - "XML::XML2JSON"
      #- "XDI"
      - "Term::ReadKey"
      - "Term::ReadLine::Perl"
      - "Schedule::Cron"
      - "Net::SMTP::Server"
      - "Net::OAuth::Simple"
      - "MongoDB"
      - "Mobile::UserAgent"
      - "Math::Combinatorics"
      - "MIME::QuotedPrint::Perl"
      - "IPC::Lock::Memcached"
      - "HTML::Query"
      - "HTML::ParseBrowser"
      - "Geo::StreetAddress::US"
      - "DateTime::Event::Cron"
      - "Data::Diver"
      - "Crypt::RC4::XS"
      - "Carp::Assert::More"
      #- "Bundle::CPAN"
      - "Apache2::xForwardedFor"
      - "Amazon::S3"

    rpm_packages:
      - perl-XML-SAX
      - perl-File-Which
      - perl-Term-ReadLine-Gnu
      - mod_perl
      - perl
      - perl-AnyEvent
      - perl-AnyEvent-HTTP
      - perl-Apache-DBI
      - perl-Apache-Session
      - perl-BSD-Resource
      - perl-Cache-Memcached
      - perl-CGI
      - perl-Clone
      - perl-Crypt-OpenSSL-RSA
      - perl-Crypt-OpenSSL-X509
      - perl-Data-Dumper
      - perl-Data-OptList
      - perl-DateTime
      - perl-DateTime-Format-HTTP
      - perl-DateTime-Format-ISO8601
      - perl-DateTime-Format-Mail
      - perl-DateTime-Format-RFC3339
      - perl-Digest-MD5
      - perl-Digest-SHA
      - perl-Email-MIME
      - perl-Email-Simple
      - perl-ExtUtils-XSBuilder
      - perl-File-Find-Rule
      - perl-File-Slurp
      - perl-HTML-Template
      - perl-Inline
      - perl-IO-Compress
      - perl-JavaScript-Minifier
      - perl-JSON-XS
      - perl-libwww-perl
      - perl-Log-Dispatch
      - perl-Log-Log4perl
      - perl-Math-Round
      - perl-Net-Twitter-Lite
      - perl-Parallel-ForkManager
      - perl-Proc-Daemon
      - perl-Proc-PID-File
      - perl-Scalar-List-Utils
      - perl-Schedule-Cron-Events
      - perl-Test-Deep
      - perl-Test-LongString
      - perl-Test-Simple
      - perl-Text-CSV
      - perl-URI
      - perl-WWW-Mechanize
      - perl-XML-XPath
      - perl-YAML-LibYAML
      - uuid-perl

  tasks:
    - name: install rpm packages
      yum: name={{ item }} state=installed
      with_items: "{{ rpm_packages }}"

    - name: install cpan packages
      cpanm: name={{ item }}
      with_items: "{{ cpan_packages }}"
